# Train test split
train_test_split:
  test_size: 0.2
  random_state: 0

# Configuration for the XGBoost Classifier
model_params:
  # General parameters
  n_estimators: 50                   # Number of trees in the ensemble
  learning_rate: 0.3                  # Step size shrinkage
  max_depth: 3                        # Maximum depth of trees
  min_child_weight: 1                  # Minimum sum of instance weights in a child
  gamma: 0                             # Minimum loss reduction to make a further partition
  subsample: 1                         # Fraction of samples to use for each tree
  colsample_bytree: 1                  # Fraction of features to use for each tree
  colsample_bylevel: 1                 # Subsample ratio of columns for each split in each level
  colsample_bynode: 1                  # Subsample ratio of columns for each split in each node
  
  # Class imbalance parameters
  scale_pos_weight: 1                  # Controls the balance of positive and negative weights

  # Learning objective and metrics
  base_score: 0.5                      # Initial prediction score for all instances
  objective: 'reg:squarederror'        # Learning objective
  eval_metric: 'logloss'               # Evaluation metrics for validation data
  
  # Multi-class settings
  num_class: 9                         # Number of classes (for multi-class problems)

  # Tree construction options
  tree_method: 'auto'                  # Tree construction algorithm
  booster: 'gbtree'                    # The booster to use
  grow_policy: 'depthwise'             # Growth policy for the tree
  
  # Regularization parameters
  alpha: 0                             # L1 regularization term on weights
  lambda: 1                            # L2 regularization term on weights

  # Other parameters
  n_jobs: 1                            # Number of parallel threads used to run XGBoost
  random_state: 42                     # Seed for reproducibility
  verbosity: 1                          # Verbosity of messages
  max_bin: 128                        # Maximum number of discrete bins for histogram-based algorithms
  enable_categorical: false             # Enable categorical features support